export const ACTIVATE_ENTRY: 'ACTIVATE_ENTRY' = 'ACTIVATE_ENTRY';
export const AUTHENTICATE: 'AUTHENTICATE' = 'AUTHENTICATE';
export const EXPAND_URL: 'EXPAND_URL' = 'EXPAND_URL';
export const RECEIVE_CATEGORIES: 'RECEIVE_CATEGORIES' = 'RECEIVE_CATEGORIES';
export const RECEIVE_CONTENTS: 'RECEIVE_CONTENTS' = 'RECEIVE_CONTENTS';
export const RECEIVE_CREDENTIAL: 'RECEIVE_CREDENTIAL' = 'RECEIVE_CREDENTIAL';
export const RECEIVE_FULL_CONTENT: 'RECEIVE_FULL_CONTENT' = 'RECEIVE_FULL_CONTENT';
export const RECEIVE_SUBSCRIPTIONS: 'RECEIVE_SUBSCRIPTIONS' = 'RECEIVE_SUBSCRIPTIONS';
export const RECEIVE_UNREAD_COUNTS: 'RECEIVE_UNREAD_COUNTS' = 'RECEIVE_UNREAD_COUNTS';
export const REVOKE_CREDENTIAL: 'REVOKE_CREDENTIAL' = 'REVOKE_CREDENTIAL';
export const RUN_IN_BACKGROUND: 'RUN_IN_BACKGROUND' = 'RUN_IN_BACKGROUND';

export namespace HISTORY {
    export const PUSH: 'HISTORY/PUSH' = 'HISTORY/PUSH';
    export const REPLACE: 'HISTORY/REPLACE' = 'HISTORY/REPLACE';
    export const GO: 'HISTORY/GO' = 'HISTORY/GO';
    export const GO_BACK: 'HISTORY/GOBACK' = 'HISTORY/GOBACK';
    export const GO_FORWARD: 'HISTORY/GOFORWARD' = 'HISTORY/GOFORWARD';
}
