export default {
    AUTHENTICATE: 'AUTHENTICATE',
    GET_SUBSCRIPTIONS: 'GET_SUBSCRIPTIONS',
    GET_SUBSCRIPTIONS_CACHE: 'GET_SUBSCRIPTIONS_CACHE',
    GET_UNREAD_COUNTS: 'GET_UNREAD_COUNTS',
    GET_UNREAD_COUNTS_CACHE: 'GET_UNREAD_COUNTS_CACHE',
    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_CATEGORIES_CACHE: 'GET_CATEGORIES_CACHE',
    SELECT_STREAM: 'SELECT_STREAM'
}
