export default {
    ACTION_DONE: 'ACTION_DONE',
    ACTION_FAILED: 'ACTION_FAILED',
    CATEGORIES_RECEIVED: 'CATEGORIES_RECEIVED',
    CONTENTS_RECEIVED: 'CONTENTS_RECEIVED',
    CREDENTIAL_RECEIVED: 'CREDENTIAL_RECEIVED',
    FULL_CONTENT_RECEIVED: 'FULL_CONTENT_RECEIVED',
    STREAM_SELECTED: 'STREAM_SELECTED',
    SUBSCRIPTIONS_RECEIVED: 'SUBSCRIPTIONS_RECEIVED',
    UNREAD_COUNTS_RECEIVED: 'UNREAD_COUNTS_RECEIVED'
}
