export default {
    ACTION_DONE: 'ACTION_DONE',
    ACTION_FAILED: 'ACTION_FAILED',
    AUTHENTICATED: 'AUTHENTICATED',
    SUBSCRIPTIONS_RECEIVED: 'SUBSCRIPTIONS_RECEIVED',
    UNREAD_COUNTS_RECEIVED: 'UNREAD_COUNTS_RECEIVED',
    CATEGORIES_RECEIVED: 'CATEGORIES_RECEIVED'
}
